[project]
name = "cossup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.42.74",
    "docling>=2.81.0",
    "httpx>=0.28.1",
    "pydantic-ai>=1.61.0",
    "pypdf2>=3.0.1",
    "ruff>=0.14.9",
]

[dependency-groups]
dev = [
    "ruff>=0.16.4",
    "ty>=0.0.78",
]
